### ISSUE TITLE
[3x3 Launcher] Hangs after swiping to lower overshoot

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroid-launcher#134]
When swipong to the bottom and overshooting, the launcher only shows half.
And trying to use it by swioing forth and back from the watchface then results in a ceres session crash after a while.

https://user-images.githubusercontent.com/15074193/232624740-9b7d71bf-cee8-45bf-9426-c4c3d4a2d1c5.mp4

**Comment by MagneFire** [comment]
Is this still an issue? I can't seem to reproduce it on `beluga`.
I thought that it was fixed by https://github.com/AsteroidOS/asteroid-launcher/commit/ddf1c102193eb214173aaf4a4fb750e95215c5bd but this issue is dated after that commit was merged...

**Comment by beroset** [comment]
I can't reproduce this either on `catfish`.

**Comment by eLtMosen** [comment]
Its not device depended and yes, i have observed it recently. 
Will be able to test again on sunday.

**Comment by beroset** [comment]
> Its not device depended and yes, i have observed it recently. Will be able to test again on sunday.

If you can both crash it and grab a log, that would probably help a lot.  Thanks!

**Comment by beroset** [comment]
The recent fix seems to address the scrolling issue nicely.  @eLtMosen, can you verify that you can no longer get it to crash?

**Comment by eLtMosen** [comment]
I have now thoroughly tested on the above shown lenok and can confirm that the issue is solved!
Thanks everyone for fixing my sloppiness. Especially @dodoradio
