### ISSUE TITLE
Port to Cmake

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroid-launcher#139]
I am failing to compile asteroid-laucher using `qmake`
```
$ qmake
Info: creating stash file /home/mo/Git/asteroid-launcher/.qmake.stash
Project ERROR: lipstick-qt5 development package not found
```
Would be great if this could be compiled using Cmake like most of the other projects in the meanwhile.

**Comment by beroset** [comment]
This was done in https://github.com/AsteroidOS/asteroid-launcher/pull/141
Thanks, all for the quick action on this!
