### ISSUE TITLE
Homescreen is empty when no nightstand WF is chosen and cha

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroid-launcher#140]
When we enable nightstand in settings.
Then enable custom watchface option.
But do not select a custom watchface -> the homescreen is empty when a charger is connected.

It looks to me that there is no default custom Watchface set which is chosen already when the option is enabled.
Imo, this should always be the currently selected regular watchface for consitency.

**Comment by MagneFire** [comment]
Obviously, your first paragraph describes a bug, that was recently introduced.

But essentially following the currently selected watchface might not work either. As someone might've selected a different custom watchface before. Toggling the custom watchface option would override the previously selected nightstand watchface.
Doing this only when no previous nightstand watchface is selected might be the better method. But it makes it seem as if the custom watchface is not selected.

Instead, it might make sense to have two flows, one when no nightstand watchface was set (default) and one where a previous nightstand watchface was set.

When default:
- nightstand watchface follows regular watchface.
- enabling the custom watchface immediately show a watchface selection.

When a previous nightstand watchface was selected:
- keep behavior as it is currently.

**Comment by beroset** [comment]
I've addressed the bug by changing the default nightstand watchface to one that is currently included.  I suspect that the proposed change would add complexity without much benefit.  At the moment, the behavior is both straightforward and easy to describe:

1. if nightstand mode is enabled, use the selected watchface
