### ISSUE TITLE
Launcher noticeably slow/choppy if there is a large number of pending notifications

### ISSUE THREAD

**Issue by atalax** [AsteroidOS/asteroid-launcher#18]
If there is large amount of pending notifications (order of tens) in the notification list, asteroid-launcher becomes really choppy.

**Comment by 2Belette** [comment]
confirmed on my side as well!

**Comment by FlorentRevest** [comment]
The new notifications center ( https://github.com/AsteroidOS/asteroid-launcher/commit/f5990b02e64db2f9933a88cd4f4f60a001a4b3a1 ) has been tested with more than 20 notifs without causing any problem. I'll close this issue now
