### ISSUE TITLE
Asteroid-launcher are not shipped in spanish translate.

### ISSUE THREAD

**Issue by Caballlero** [AsteroidOS/asteroid-launcher#20]
- Dev build 06 may. Just notifying  ...

**Comment by FlorentRevest** [comment]
Thanks for reporting. Fixed in https://github.com/AsteroidOS/asteroid-launcher/commit/b23e671e1ef147ccbebad5885532f16b09b73b1c

**Comment by Caballlero** [comment]
Thank you.
