### ISSUE TITLE
Analog watchface does not update with time

### ISSUE THREAD

**Issue by brycehenley** [AsteroidOS/asteroid-launcher#31]
When enabling the anolog watchface it sets the correct time but never changes to reflect the time. This does not seem to be related to locking, maybe this is due to it not repainting the screen. I have reproduced this issue every time I have set the watchface to analog.

**Comment by FlorentRevest** [comment]
Hi brycehenley,
Thanks for reporting! This issue is probably to be linked with https://github.com/AsteroidOS/asteroid-launcher/issues/30 If you think you can solve it yourself, feel free to send a PR to asteroid-launcher.
I'll keep it open for now.

**Comment by eLtMosen** [comment]
i am on it tomorrow ;) Same fix as with analog-precision from unofficial-watchfaces repo propably!

**Comment by FlorentRevest** [comment]
@eLtMosen, do you still have plans to fix this issue?

**Comment by eLtMosen** [comment]
oh right, i obviously forgot.
Matter of hours until i send PR.

**Comment by eLtMosen** [comment]
#32
