### ISSUE TITLE
[Feature Request] WatchFaces with capability to display weather

### ISSUE THREAD

**Issue by Doomsdayrs** [AsteroidOS/asteroid-launcher#52]
Currently, to view the weather, one must turn on the watch, swipe from the right side of the screen left, and then read the tiny weather bubble.

This is plenty of extra steps to just *view* how hot it is today.

**Comment by MagneFire** [comment]
This is actually something we would like to solve by implementing WatchFace Complications (https://github.com/AsteroidOS/asteroid/issues/136).
From my understanding, you would also like to see the weather when the screen is in Always-on-Display mode?

**Comment by eLtMosen** [comment]
This is a matter of creating a watchface with weather display.
The complications are purely hypothetical right now and would also require custom watchfaces with spots for those complication items reserved.
I'll look into creating a watchface with weather info suitable to be included in 2.0.

**Comment by eLtMosen** [comment]
This the the current candidate. 
https://github.com/AsteroidOS/unofficial-watchfaces/pull/87
Its merged into the unofficial repo solely since it has some features that are to be removed for stock inclusion.
Keeping this issue open until its merged to stock.

**Comment by eLtMosen** [comment]
The merge of the newly created `analog-weather-satellite` will solve this issue.
https://github.com/AsteroidOS/asteroid-launcher/pull/128

A satellite/complication system to add weather info to any watchface that then supports the satellites/complications system is discussed here:
https://github.com/AsteroidOS/asteroid/issues/136
