### ISSUE TITLE
[Bug] [UI] Color shift from applications list remains after pressing power button with stock wallpaper

### ISSUE THREAD

**Issue by Doomsdayrs** [AsteroidOS/asteroid-launcher#55]
Steps to reproduce:
1. Swipe into application list, observe color of the background change
2. Press power button while in the application list, AOD WatchFace starts
3. Press power button once more, turning the screen on and observe that the home screens UI is color shifted to the color as of step 1.

Expected:
1. Swipe into application list, observe color of the background change
2. Press power button while in the application list, AOD WatchFace starts
3. Press power button once more, return to the original background color

**Comment by MagneFire** [comment]
Solved by https://github.com/AsteroidOS/asteroid-launcher/commit/e3600d57d8db013299635939d01fdb9eab098d0b and https://github.com/AsteroidOS/asteroid-launcher/commit/95ce4f5b5ea30736ce9ebb150b028cbc04da0c54 (fix whoopsie).
