### ISSUE TITLE
Font size of words watchface too big

### ISSUE THREAD

**Issue by romainreignier** [AsteroidOS/asteroid-launcher#7]
The font size of the watchface `words` is a little too big for the screen (width) of the LG G Watch (Dory) on "Twenty-five" for example. Decreasing the font size of few points should be enough.

**Comment by romainreignier** [comment]
I took a picture to show the issue.

![img_20161130_022630280](https://cloud.githubusercontent.com/assets/8845664/20736110/c82878ee-b6a4-11e6-9aa8-d1cb297d2c6c.jpg)

**Comment by FlorentRevest** [comment]
Thanks, closed by bf37b85d45fa709c122511619df9f615dfbe9f75
