### ISSUE TITLE
Unify App-Colors

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroid-launcher#84]
After recent addition of 3 apps to the stock selection, it became apparent that those need to be re-colored to fit into the original rainbow color scheme. On closer look during selecting colors for those, the idea to darken down the whole color scheme to provide better contrast to UI elements in all apps was tested in depth and lead to following proposed colors for the individual apps.
The trade off clearly is loosing some of the more vivid orange and pink tones in favour of better legibility.
In this attempt, those colors have been darkened down to the point where color characteristics should still be nicely recognisable on OLED screens. Then orientate all other colors to that brightness and contrast level to prevent "bumps" during scroll in the app-drawers.

[App-Colors itteration 7, Test5](https://mosushi.de/misc/asteroidos/app-colors/colors5.htm)

.Desktop files to test all on device:
[asteroid-I7.zip](https://github.com/AsteroidOS/asteroid-launcher/files/8054605/asteroid-I7.zip)

Now starting to do individual PR per app, to be tracked here.
Please discuss the actual colors in those PRs. General implementation and discussion regarding the whole palette in this issue.
| Initial PR | Color Approved |
|---|---|
| <ul><li>[x] Agenda</li></ul> | <ul><li>[ ] ?</li></ul> |
| <ul><li>[x] Alarm Clock</li></ul> | <ul><li>[ ] ?</li></ul> |
| <ul><li>[x] Calculator</li></ul> | <ul><li>[x] ?</li></ul> |
| <ul><li>[x] Compass</li></ul> | <ul><li>[x] ?</li></ul> |
| <ul><li>[x] Diamonds</li></ul> | <ul><li>[x] ?</li></ul> |
| <ul><li>[x] Flashlight</li></ul> | <ul><li>[x] ?</li></ul> |
| <ul><li>[x] Heart Rate</li></ul> | <ul><li>[x] ?</li></ul> |
| <ul><li>[x] Music</li></ul> | <ul><li>[x] ?</li></ul> |
| <ul><li>[x] Settings</li></ul> | <ul><li>[x] ?</li></ul> |
| <ul><li>[x] Stop Watch</li></ul> | <ul><li>[x] ?</li></ul> |
| <ul><li>[x] Timer</li></ul> | <ul><li>[x] ?</li></ul> |
| <ul><li>[x] Weather</li></ul> | <ul><li>[x] ?</li></ul> |

**Comment by FlorentRevest** [comment]
Not much to discuss :)

I feel that for 90% of the apps this is a very clear net improvement when taken individually.
And even though it feels like some sort of regression for a couple of apps (agenda and alarm clock in my opinion) this is still a big win in terms of overall consistency (same brightness everywhere) and readability (much better text contrast, especially outside).

So thanks a lot, this is a terrific improvement to the overall UI of Asteroid, it will be great to show off! :D

**Comment by MagneFire** [comment]
This should be all implemented now. Feel free to reopen if I made a mistake :P
