### ISSUE TITLE
Time in default watchface is shown doubled (tetra)

### ISSUE THREAD

**Issue by Etua** [AsteroidOS/asteroid-launcher#9]
Shortly after installing Asteroid I've noticed small, yet annoying bug. The time is fixed on some state and the real hour is shown under it. Changing the watchface fixes the bug by the time of the screen power off. After turning it on again, the real hour is placed under the hour of screen power off. 
In the picture only wrong minutes are visible (35), but the bug affects both the hours and the minutes.

![img_20161210_235208](https://cloud.githubusercontent.com/assets/13040148/21076777/6fed43f6-bf34-11e6-8630-ef4de35396b0.jpg)

**Comment by FlorentRevest** [comment]
This issue (with some other graphical glithces on tetra) has been fixed a couple of weeks ago.
