### ISSUE TITLE
Focus issue with rotating input

### ISSUE THREAD

**Issue by dodoradio** [AsteroidOS/asteroid-launcher#92]
on watches with a rotating crown (narwhal, ray/firefish) the rotating crown seems to suffer from a focus issue when opening apps. After tapping the screen after entering an application with some flickable-derived panel, the scroll wheel works fine, but it will not work until the screen is tapped. This seems to be an issue with the compositor not transferring focus correctly.

**Comment by MagneFire** [comment]
I did some debugging in the past, among them was not using our launcher at all.
You can use `qmlscene` with the `hwcomposer` backend as well. This also had the focusing issue.
It might be something in Qt itself or we might be missing something else.
You can try this yourself by pushing `qmlscene` from the `qtdeclarative` build files and running like so:
```
$ systemctl --user disable --now asteroid-launcher
$ EGL_PLATFORM=hwcomposer QT_QPA_PLATFORM=hwcomposer qmlscene crown-test.qml
```

The next step might be to try a non-Qt application like SDL2 and check if that works as expected.

Relevant source issue: https://github.com/AsteroidOS/asteroid/issues/174
